### ISSUE TITLE
Star view metric information/key can occlude stars

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#130]
Suggest that scale and other metrics pertaining to the star view NOT be integrated to (and turn with) the labels and the field, but be pushed to the bottom or top margin. As it is, any stars that rotate over them have their data/name/visibility compromised. 

Given how many stars may be desired in view (expanding the radius), this effect gets much more noticeable. What may look like visual simplicity at this scale becomes essential as the radius of view expands and star density in view increases
![view metric compromises readability](https://user-images.githubusercontent.com/69170614/95144753-6f852000-0747-11eb-8565-2501c141c22b.png)
.

**Comment by ljramones** [comment]
you can toggle the scale and other items so that they disappear
here is the scale showing
![image](https://user-images.githubusercontent.com/226595/95146272-6433f380-074b-11eb-9e28-de4fae7477fb.png)

here is with the scale toggled

![image](https://user-images.githubusercontent.com/226595/95146314-7b72e100-074b-11eb-827d-4e8fd7e837f8.png)

I think this is a case where the documentation needs to note it.

**Comment by cegannon1** [comment]
I think documentation is a good start... but most people don't read it.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cegannon1** [comment]
I think the label "scale", although it certainly is clear in retrospect, could be misinterpreted as meaning this is where you can alter "how big the view field is."

________________________________
