### ISSUE TITLE
a modifier key (shift or ctrl) would be used to modify rotation or zoom speed, offering two or three different speeds.

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#155]
used to be there, re-adding

**Comment by ljramones** [comment]
This is actually straightforward to do. 

The question I have is do we want this configurable or it is defined in the user docs and left at that

**Comment by cegannon1** [comment]
I would like to get Rick's input on this one, too.   I am wondering if there is a middle course but I do not know how difficult this would be to do. I was thinking it might be helpful that the 1st time that the cursor is placed on the function it announces that there is a reconfiguration option. And that it is detailed in the documents. I am thinking that this would be useful for the 1st encounter with the program's other reconfigurable standard settings.

Then the user has the option to turn off the notification. Until they choose To turn it off, it will keep reminding them that they have the option. But I think it needs to be turned off once they either do it, or they decide that they don't want to be bothered with the constant reminders.

I am suggesting this because I think anything that is just buried in the documentation is probably not going to get used at all. It is remarkable how few people actually read documentation, even when it is clearly written and fairly brief.

Your thoughts?
________________________________

**Comment by ljramones** [comment]
I think it would be better to have a button to push that bring up a list of screen controls and what they do.

Making this a stateful value (shows up once and then goes away) means that after a while you'll forget what it was and then you have to figure out how you got it the first time.

**Comment by ljramones** [comment]
likewise, I've defined different speeds for this capability.
We just haven't agreed on the key mappings.
I'll close this one and add the request for key mappings in another ticket
