### ISSUE TITLE
Star label loses focus as one gets closer to the star

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#24]
Related to Issue #23. When getting closer to the star and the label expands, the label also loses focus/becomes blurry.

Regardless of the size of the label, its should be crisp and readable. This screenshot is identical to the one for issue 23.
![Star label focus degradation when proximal](https://user-images.githubusercontent.com/69170614/90988546-8427a300-e561-11ea-940e-08e761e04f90.png)

**Comment by EvilJinious1** [comment]
same explanation. Its a 3D scene and while objects have a specific size and pixel density, when you zoom in on them that happens
I will have to figure out haw to dynamically change them

**Comment by BoatrightTBC** [comment]
You're probably going to have to regenerate the scene when zooming so that the APPARENT size of the labels stays the same.  

Similar to the rotation issue... although you probably don't have to re-generate the 3d scene until the rotation exceeds some value (50, 60 degrees)... but then, you pretty much have to re-gen in order to re-orient the labels to face the viewer. 

Basically, I think you need to re-gen if the zoom changes by more than "X" percent.  My first guess is 25 or 30.  Zooming out is as bad as in since the labels get smaller...   and re-gen if the scene rotates by more than THETA in any direction.

**Comment by ljramones** [comment]
label stays the same size at any range
