### ISSUE TITLE
ChView Dataset import errors 0,66 on SOME datasets - see details. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#247]
**Import failure on three distributed CHV files**

**NOTE** TERRAGRP.CHV loaded successfully, these others did not. 

100LY-H.CHV failed to import with the following information displayed on the log screen: 

```
2021-03-12 05:52:15.744 ERROR 31572 --- [       Thread-9] c.t.trips.file.chview.ChviewReader       : format corruption in file:Cannot invoke "com.teamgannon.trips.stellarmodelling.StellarClassification.getStarColor()" because "stellarClassification" is null
2021-03-12 05:52:15.815 ERROR 31572 --- [lication Thread] c.t.t.s.i.CHVDataImportService           : dataset load failed due to: Not on FX application thread; currentThread = Thread-9
2021-03-12 05:52:20.291 ERROR 31572 --- [lication Thread] c.teamgannon.trips.support.AlertFactory  : failed to load dataset: chv100, because of dataset load failed due to: Not on FX application thread; currentThread = Thread-9
```
SOPHONTS.CHV failed to import with the following error in the log screen: 

```
2021-03-12 05:48:47.375 ERROR 31572 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : format corruption in file:Cannot invoke "com.teamgannon.trips.stellarmodelling.StellarClassification.getStarColor()" because "stellarClassification" is null
2021-03-12 05:48:47.404 ERROR 31572 --- [lication Thread] c.t.t.s.i.CHVDataImportService           : dataset load failed due to: Not on FX application thread; currentThread = Thread-7
2021-03-12 05:50:36.067 ERROR 31572 --- [lication Thread] c.teamgannon.trips.support.AlertFactory  : failed to load dataset: CHV SOPHONTS, because of dataset load failed due to: Not on FX application thread; currentThread = Thread-7
```
The following datasets also failed at the same point with the same error: 
25LY-H.CHV, farexile.chv, polities.chv 

All of them display this when they freeze. 

![import chv error](https://user-images.githubusercontent.com/20006248/110938313-4b7ec980-82f9-11eb-8a7d-1978b5ed7bd4.png)

The cancel import button is disabled. The close button works, and the program proceeds without having imported anything.

**Comment by ljramones** [comment]
ok, I'll look at it.

**Comment by ljramones** [comment]
Here is a general question.
I am going through the CHV processing and found that some spectra are coming back as Q, ? and d. By default I am mapping these to M class. If you want them to be mapped otherwise, let me know.

**Comment by BoatrightTBC** [comment]
Works for me, we have to guess anyway, and the only point of this is to load the OLD data so we can see where polities are & etc.

________________________________

**Comment by ljramones** [comment]
Here is a general question.
I am going through the CHV processing and found that some spectra are coming back as Q, ? and d. By default I am mapping these to M class. If you want them to be mapped otherwise, let me know.

**Comment by ljramones** [comment]
ok, I figured out the issue.
I also discovered that I need to add the label handling logic to the CHV file imports. I have it for CSV and Excel but not the CHV ones

**Comment by ljramones** [comment]
here are the bad spectral values for CHV
     : Could not figure out stellar classification: spectra =PseudoString(value=Q9VIId, length=8, name=true)
2021-03-12 14:27:59.699 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q7VIId, length=8, name=true)
2021-03-12 14:28:01.424 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q9VIId, length=8, name=true)
2021-03-12 14:28:05.398 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=QP8VIId, length=9, name=true)
2021-03-12 14:28:14.185 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q6VIId, length=8, name=true)
2021-03-12 14:28:27.977 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q9VIId, length=8, name=true)
2021-03-12 14:28:29.315 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=QP9VIId, length=9, name=true)
2021-03-12 14:28:36.912 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q8VIId, length=8, name=true)
2021-03-12 14:28:39.869 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q6VIId, length=8, name=true)
2021-03-12 14:28:44.349 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q8VIId, length=8, name=true)
2021-03-12 14:28:45.026 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q6VIId, length=8, name=true)
2021-03-12 14:28:45.575 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q6VIId, length=8, name=true)
2021-03-12 14:28:46.256 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q5VIId, length=8, name=true)
2021-03-12 14:28:46.863 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q5VIId, length=8, name=true)
2021-03-12 14:28:47.533 ERROR 8328 --- [       Thread-7] c.t.trips.file.chview.ChviewReader       : Could not figure out stellar classification: spectra =PseudoString(value=Q8VIId, length=8, name=true)

I'm not sure why he would use this mapping

**Comment by BoatrightTBC** [comment]
Is "Q" his signal for a fake star I wonder?
________________________________

**Comment by ljramones** [comment]
its the "QP8VIId" that confuses me. That is so exacting for a mystery star

**Comment by ljramones** [comment]
want me to allocate a default specific spectral class for it?

**Comment by BoatrightTBC** [comment]
no, it was just a thought.  Use M.

He's just weird, as we had already established.

________________________________

**Comment by ljramones** [comment]
sure

**Comment by cegannon1** [comment]
The answer should be on his Sol Station website. I'll go look. Feed me a list of the mystery spectra.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cegannon1** [comment]
Not yet. Lemme.research his site.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
@cegannon1 here are the values TRIPS barfed on

Q7VIId
Q9VIId
QP8VIId
Q9VIId
Q6VIId
Q5VIId
Q8VIId

**Comment by cegannon1** [comment]
No wait. I'm  researching.  And I have a guess...

that Q = suspected quasar

P= suspected.pulsar

I'll let you know asap

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cegannon1** [comment]
Hmm...can you give me complete examples and the Chv dataset in which they are found?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
do you want the full record that includes that spectra type?
I was doing testing on the 100 ly dataset

**Comment by cegannon1** [comment]
please

**Comment by cegannon1** [comment]
That is probably going to work. Here’s where the weird spectrum factors come from. Read the first para here. It suggests these may be very old catalog objects. Are they the only rating for the star? Does the star have multiple names/catalog codes?

https://astronomy.swin.edu.au/cosmos/h/harvard+spectral+classification

**Comment by cegannon1** [comment]
This gives a little more insight into old records (The Ballmer line classification system that included Q)  as well as modern variants, most of which are modifications to D classification (read down for that). It’s a Wiki and I wouldn’t trust it entirely. But it’s a good springboard.

https://space.fandom.com/wiki/Stellar_classification


Rick, this is the moment when my expertise (all things CHV) must give way to one of your areas of specialty (spectra and their classifications). Hopefully, this is the lead that will allow us to tease out what is going on.

Best,
chuck

**Comment by ljramones** [comment]
a month ago, I write a full spectral class parser that takes into account the extended classes, the luminosity, the multiplier i.e. G3.5IV, the peculiarities, hydrogen lines, etc.
So if the spectral class is properly defined, my parser will handle it correctly.

Here is the regex parser that deals with it.

    private final String prefixPatternStr = "^(sd|sg|d|c|g)";
    Pattern prefixPattern = Pattern.compile(prefixPatternStr);

    private final String curlyBracketsStr= "\\{(.*?)\\}";
    Pattern curlyBracketsPattern = Pattern.compile(curlyBracketsStr);

    private final String regBracketsStr= "\\((.*?)\\)";
    Pattern regBracketsPattern = Pattern.compile(regBracketsStr);

    //private String classPatternStr = "^(O|B|A|F|G|K|M|L|T|Y|P|Q|WN|WC|WR|DA|DQ|DB|DZ|DO|DC|DX|C\\-R|C\\-N|C\\-J|C\\-H|C\\-Hd)d(\\.d)";
    private final String classPatternStr = "^(O|B|A|F|G|K|M|L|T|Y|P|Q|WN|WC|WR|DA|DQ|DB|DZ|DO|DC|DX|C\\-R|C\\-N|C\\-J|C\\-H||C\\-Hd)(\\d(\\.\\d)?)?";
    Pattern classPattern = Pattern.compile(classPatternStr);

    private final String yerkesPatternStr = "^(0|Ia\\+|Ia|Iab|Ib|II|III|IV|V|VII|VIII|IX|X)";
    Pattern yerkesPattern = Pattern.compile(yerkesPatternStr);

    private final String pecularitiesPatternStr = "^(:|...|!|comp|e|\\[e\\]|er|eq|f|f\\*|f\\+|\\(f\\(|\\(f\\+\\)|\\(\\(f\\)\\)|\\(\\(f\\*\\)\\)|h|ha|He wk|k|m|n|nn|neb|p|pq|q|s|ss|sh|var|wl)";
    Pattern pecularitiesPattern = Pattern.compile(pecularitiesPatternStr);

**Comment by cegannon1** [comment]
This resource makes me wonder if Q is actually now ~ to one of the sub M types.

Search for “Balmer” to find the relevant sections for starting:

https://www.e-education.psu.edu/astro801/book/export/html/1755

**Comment by cegannon1** [comment]
Hi Larry:

What I mean is: specific stars with the Q spectral qualifier. I’ll then go into the CHV I can get running on my machine. The notes for the star are often tied to Sol Station entries. I should be able to data mine.

Just give me specific stars, by name, and tell me if they are in the 100 LY set or 150 or etc.

Thanks,

Chuck

**Comment by ljramones** [comment]
I sent a separate email with the full list of strange spectra and the records associated with the spectral class

**Comment by ljramones** [comment]
all fixed. got all the CHV files to load. For those with weird spectral classes. I defaulted to M class until you guys make a decision.

<img width="1475" alt="CleanShot 2021-03-13 at 10 23 38@2x" src="https://user-images.githubusercontent.com/226595/111035013-39c72000-83e6-11eb-9eef-72dd3ffb833e.png">

**Comment by cegannon1** [comment]
Hi Larry:

Okay, once I saw the CHV data, I realized something.

We don’t need to keep this data. Reason follows.

Practical instruction:

Simply create   “?” as a recognized spectral class.

And then all the faulty spectral classes you list below should simply be converted to  ? .


Reasons:

Firstly, it turns out that the “Q” value is almost certainly a holdover from catalog listings that are almost 100 years out of date. That means that the observational methodologies are equally ancient.
Q was part of a precursor spectral classification system that preceded the one we use today. It was based on hydrogen fusing lines in spectroscopic observations of the stars, and ran from A-R, I think.
Q would *usually* indicate a faint object, which is probably why a great number of these faulty Spectrascopic classes are observed with closer rather than farther objects.

But since then, so much has changed (accuracy of parallax, accuracy of spectroscopy, accuracy of damn near EVERY observational metric) that we can’t be sure about ANY of these values which were generated using methods that are museum pieces.

Furthermore, this data is in CHV. Meaning that, if the star name syncs up with the/a star name or catalog code in the Gaia/Simbad/Hipparcos 2 data, none of it is going to be imported anyhow. All these classifications will get scraped off anyhow.

Best of all, using  “ ? “ as a spectral class actually solves ANOTHER issue; how to code stellar objects in the Gaia data for which there are not spectral classes generated. Rick and I have worked out a pretty fair “approximation via statistical Kentucky windage” method of assigning everything a spectral class in the FICTIONAL / TERRAN REPUBLIC data. But in the “virgin Gaia” dataset (or any derived therefrom) lack of spectral class should be notated as such. And this answers that challenge.

Any questions? Just ask.

Best and thanks,

Chuck

**Comment by ljramones** [comment]
Hi

Ok, however a few caveats.

Point 1) ? Is a reserved character for pattern processing. I would rather not use it. I would have to escape it everywhere and that would mean lots of changes in the lexical analyzers.

How about I change the “?” To an X and handle it that way. X for the great unknown.

Point 2) I need a default set of spectral properties for the X class. Should I treat it as a M class or something else. M class is our sort of default condition.

**Comment by cegannon1** [comment]
Rick, this has gone my competence.

Again.

re.1) X is not good.

re 2) why must it have any properties, other than just being a distinctive handle?

 thanks,

Chuck

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
Ok, I can make the changes to use ? but the risk associated with it pushes the release for v0.6.7 to at least Wednesday. It's a lot of changes and I have to do a lot more testing.

The reason is that everything is governed by how the lexical analyzer parse the spectral class. "?" is a reserved character and I have to write a lot of extra stuff to deal with it.

As to default spectral properties. I need a color to plot ? as. Computer programs are exact things. No hand waving allowed. So if I have to plot ?, I need to know what to color it as.

I could just not plot it and that would work.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ljramones** [comment]
just so you know what the list of reserved characters, here they are

. ? ( ) {} [] ^ * \

Whenever you use one of these as a search character, you have to escape it. Its a pain in the ass, but doable. I already escape () and {} because some of the files use these in the the spectral class definitions

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cegannon1** [comment]
Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ljramones** [comment]
I will make the changes.

Hopefully I can finish tomorrow.

**Comment by cegannon1** [comment]
But haven't given you character or color yet.

I am in a bad home situation and I just can't do more tonight.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cegannon1** [comment]
Plot "unk"  same color as M since M is the most common and we're just
guessing.

Plot Q, P, and all the D's as the same color as O since they're all white
dwarfs and thus HOT tho tiny.

If you could plot Q, P and D as the same color as O but the same size as K,
that would be perfect unless you wanted to add them to the list of things
in setup to do colors and radius for.  In any event, they're not as big as
O's.

If you do want to add them that way, you can put all 3 on the same line
since they're all 3 white dwarfs.
