### ISSUE TITLE
Grid shifts left when side pane opened

### ISSUE THREAD

**Issue by celebrith** [ljramones/trips#265]
**Describe the bug**

When you open the side pane, the grid shifts left.  This leaves a lot of dark space to the right of the grid and the grid is no longer centered.

**To Reproduce**

1. Plot stars
2. Click on the "Side Pane" button

**Expected behavior vs Actual**

I expected the side pane to open over the grid, with the grid remaining centered (especially with the "Center on this star" function).
Instead it shifts the entire display left, cutting off part of the grid on the left (depending on the grid size) and offsetting the center of the grid.  This is somewhat confusing.

**Screenshots**

If applicable, add screenshots to help explain your problem. If none, delete this section. You will have to have saved screenshots to your local drive, then just drag and drop them to here in the editor. 

**TRIPS version** 
- [ ] 0.52 
- [ ] 0.53
- [ ] 0.54
- [ ] 0.55
- [X] 0.6.7 

**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [ ] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 
- [X] macOS Big Sur 11.2.3 (Apple Silicon running in Rosetta 2)

**Additional info **

Certainly not a show-stopper, but it would be nice if it were possible to draw the side pane over the grid image rather than shifting the grid image left to "make room" for the side pane.

**Comment by BoatrightTBC** [comment]
Let's make sure we know what we want. 

Start with just a sphere of stars. 
![Screen1](https://user-images.githubusercontent.com/20006248/111945503-d1dc9d80-8aa7-11eb-9798-d595acbb4a8d.jpg)


Then, open the side-pane without doing anything 
![Choice 1 - do  not re-draw](https://user-images.githubusercontent.com/20006248/111945522-dd2fc900-8aa7-11eb-88b8-22fe5a1454f8.jpg)


Or-recenter in the remaining space 
![Recenter](https://user-images.githubusercontent.com/20006248/111945540-e6209a80-8aa7-11eb-82e8-81ae7465735d.jpg)


This is more obvious if we use a 
### Very zoomed in star field. 
![Zoomed 1](https://user-images.githubusercontent.com/20006248/111945554-ed47a880-8aa7-11eb-9a20-f8a53da6f42e.jpg)

### Do nothing 
![Zoomed Do nothing](https://user-images.githubusercontent.com/20006248/111945582-f769a700-8aa7-11eb-8001-bb5a3f1d3fb8.jpg)
OK, that sucks. 

### Shove over 
![Zoom shift Left](https://user-images.githubusercontent.com/20006248/111945620-07818680-8aa8-11eb-83f7-ab2b971ac0ea.jpg)

This is better, and I think it's what you're doing now but people keep asking for something else... like 

### Re-center 
![Zoom Re-center](https://user-images.githubusercontent.com/20006248/111945643-0ea89480-8aa8-11eb-8c92-b7d12c003965.jpg)

We really want to re-center. 

Larry, you've said before that you're shifting the image left and right by X pixels, but I really think we have to re-draw in whatever rectangle's LEFT after opening the side pane.  

I suspect that you're layering the side-pane over the top of the drawing pane rather than dumping the old-drawing pane and creating a NEW drawing pane of the new dimensions and putting on the left side, and creating a new size pane at the SAME z level as the drawing pane and then re-drawing.  

If that's not the problem, could you explain it to us?

**Comment by ljramones** [comment]
Here is how the graphics works. 
I define a drawing area.
I perform the query and figure out the limits of the 3 D plot.
I do an affine transform the the plot to make it fit the screen so it nicely aligns to the displayed area.
The zoom in/out and rotation works with the defined screen area. I clip the element that are offscreen and clip the labels that are too close to the displayable edge.

So when you open the side panel, it normally just overlays over the plot display.
Initially, that was where it sat. I didn't do any transforms.
Two things changed...

1) In order to support a resizable screen, I had be able to:
- Make the display area change in concert with the change in frame size.
- resize the side panel and deal with keeping the perspective correct and locking it in either closed position, fix the cursor position 
- resize the plot in concert to the size change.

2) In order to shift the plot when the side panel is opened and then shift it back

It's not advisable to re-query and re-plot stars on each resize or side panel open close. Even if just deal with the results of a single query and then just re-plot, there is a significant performance impact to re-plot.

Why?
   - we have to figure out the screen size and do an affine transform against all coordinates
   - we create each of the stars based the attributes of each record
   - we create and manage the labels (determine what labels are to be calculated 
   - if there are routes, then we must redraw each route
   - if there are transits, then we must redraw each transit
   - we must update the side panel for all the values or stars, routes and ancillary data

What I do instead. 
   - Since I have all the info as a graphical buffer, I rescale and translate the contents of the screen.
   - Why: its very fast and efficient. No memory creation or collection, CPU use is minimal

Up till you wrote that description of the problem, I wasn't really sure what the issue was.
So I will work towards performing a rescale/translate that makes plot entirely enclosed in the displayable area and entered.

**Comment by cegannon1** [comment]
But it was Rick who wrote that and worked it through with you.

BTW, I don't know what an affine transform is...and I am not asking for a description. I have come to the point that I accept even if I think I understand explanations, there's still huge Gulfstream of ignorance that keep me from being able to be sure that I *actually* understand.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
There was a question in the past about changing the 3d star plot when you opened the side panel.

Rick’s extended description helped me to understand the quality of the problem he wanted solved.

My extended explanation was for him so he would understand the tradeoffs needed to do it.

An affine transformation is one where you change it without distortion.
If the plot is 30 x 30 x 40 and you have to map it into a 1000 x 700 x 400, how do you modify the plot to fit without distortion.

**Comment by BoatrightTBC** [comment]
Yes it was, but I didn't explain myself well, Larry and I were using different terms for the same thing. 

> But it was Rick who wrote that and worked it through with you.

**Comment by cegannon1** [comment]
OK, although according to the distro list that came through with the email, he wasn't one of the recipients unless he is connected to whatever comments are.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
It appears in the text of the issue like this email does

**Comment by cegannon1** [comment]
So, on Github.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by celebrith** [comment]
> Let's make sure we know what we want.
> 
> Start with just a sphere of stars.
> ![Screen1](https://user-images.githubusercontent.com/20006248/111945503-d1dc9d80-8aa7-11eb-9798-d595acbb4a8d.jpg)
> 
> Then, open the side-pane without doing anything
> ![Choice 1 - do not re-draw](https://user-images.githubusercontent.com/20006248/111945522-dd2fc900-8aa7-11eb-88b8-22fe5a1454f8.jpg)
> 
> Or-recenter in the remaining space
> ![Recenter](https://user-images.githubusercontent.com/20006248/111945540-e6209a80-8aa7-11eb-82e8-81ae7465735d.jpg)
> 
> This is more obvious if we use a
> 
> ### Very zoomed in star field.
> ![Zoomed 1](https://user-images.githubusercontent.com/20006248/111945554-ed47a880-8aa7-11eb-9a20-f8a53da6f42e.jpg)
> 
> ### Do nothing
> ![Zoomed Do nothing](https://user-images.githubusercontent.com/20006248/111945582-f769a700-8aa7-11eb-8001-bb5a3f1d3fb8.jpg)
> OK, that sucks.
> 
> ### Shove over
> ![Zoom shift Left](https://user-images.githubusercontent.com/20006248/111945620-07818680-8aa8-11eb-83f7-ab2b971ac0ea.jpg)
> 
> This is better, and I think it's what you're doing now but people keep asking for something else... like
> 
> ### Re-center
> ![Zoom Re-center](https://user-images.githubusercontent.com/20006248/111945643-0ea89480-8aa8-11eb-8c92-b7d12c003965.jpg)
> 
> We really want to re-center.
> 
> Larry, you've said before that you're shifting the image left and right by X pixels, but I really think we have to re-draw in whatever rectangle's LEFT after opening the side pane.
> 
> I suspect that you're layering the side-pane over the top of the drawing pane rather than dumping the old-drawing pane and creating a NEW drawing pane of the new dimensions and putting on the left side, and creating a new size pane at the SAME z level as the drawing pane and then re-drawing.
> 
> If that's not the problem, could you explain it to us?

Thanks, Rick (and all).  That is what I was hoping for - recentering.  I wasn't sure how difficult of an effort it is.  But just shifting the entire grid to the left cuts off some of the left of the grid while leaving a large amount of blank space between the side pane and the grid.

**Comment by ljramones** [comment]
Ok, I made changes such as dynamically calculating the central point of the current display and determining the shift point.
It shifts when the side panel and then shifts back
