### ISSUE TITLE
Highlight star does nothing if name isn't displayed. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#275]
If you click on a star, and in the context menu choose highlight star, nothing happens if that stars name isn't displayed.  

The way a star is highlighted is to blink its name at about 1 Hz.  Not useful if there's no name, and actually, not very visible in a crowded star field. 

There are a lot of things we COULD do.  I propose one of the following if it's not too hard. 
- Superimpose a six pointed Moravian star on the star's dot.  
- 
![Moravian star](https://user-images.githubusercontent.com/20006248/112096918-2433c200-8b6d-11eb-86ed-422c19ab3981.jpg)

- put a donut around the star in an obvious color. 
- 
![donut](https://user-images.githubusercontent.com/20006248/112097325-cbb0f480-8b6d-11eb-85fc-562820d812b3.jpg)

either way, a highlighted star becomes obvious

**Comment by ljramones** [comment]
Or I could make a label in a larger font appear for a period of time and blink.
That might be easier.
The Moravian star will require me to provide a mesh object to import. I am not an artist so I'll have to find a ready made mesh model 

I've experimented with toruses on the plot but they didn't look very good

**Comment by cegannon1** [comment]
Larger font is a no go. The visual field becomes too wonky at a certain point.  Most studies of cognitive recognition iand orientation indicate that you want a consistent structure with variation in luminosity or color amongst the elements to call attention to them.

My years in television drove that point home time after time. having things change shape and size is generally a great way to *disorient* the viewer. If if the object is so central that it becomes an animation that then jumps out and dominates the screen... that's different. But otherwise it is something that is called the junkyard effect. A whole lot of things that are trying to signal different values through change in shape or font or size.

You don't want to do that period

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
so have a regular label appear and blink if a star doesn't have one?

I could put a unique shape but it will take longer to do. Someone would have to find a mesh shape in either Maya, Blender or ObjectForm standard for me to load.

**Comment by cegannon1** [comment]
Rick, can you get out a request for that graphic?

Larry, better that the star blinks, possibly with slight size increase and decrease as it does . Much better.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
as an example of what I mean. Here is the sort of 3d models I am talking about
https://free3d.com/3d-models/blender

These are provided as a mesh model in a variety of different formats.
e.g Moravian: https://3dwarehouse.sketchup.com/model/180dd2ca87958ae0d5ffc86356656b05/Moravian-Star?hl=en

They can be free or have a licence: e.g. https://free3d.com/3d-model/star-sun-1319.html

So we could use a tool like this to import it for use:  http://www.interactivemesh.org/models/jfx3dimporter.html

**Comment by cegannon1** [comment]
https://3dwarehouse.sketchup.com/model/f05c35a76238ade9dd690b893fd08af/Star

https://3dwarehouse.sketchup.com/model/2e64c5eff2768c03d7e8c32507ac1777/Star

This sort of image?

Can colors be changed/neutralized?

**Comment by BoatrightTBC** [comment]
yes, that sort of model.    and yes, color has nothing to do with the 3d structure, that's just planes, vertices, and edges.  

### * For the central star (usually Sol, but we're talking about recentering a lot these days.

My best friend is a blender user, and he'll have a model for us in a day or so, essentially exactly the one I posted up top. the six pointed moravian star.  I'll have a mesh for you. 

### * For highlighting a star 

i'm still convinced that flashing the name just doesn't work for me.  Even if you turn the name on when we choose to highlight a star, flashing the name just doesn't draw my eye.  I think it pretty much has to be a shape.  

If torus don't work well on screen, and I believe that, then perhaps a different spikey thing could. Right now, we have a screen full of dots, and it turns out that cubes doen't show well enough. 

Mesh spheres are available for free...  this one probably has too many lines, but if it surrounded the core-star with a radius 3x the radius of the dot of the star in the center, then it would be "obvious." 

![image](https://user-images.githubusercontent.com/20006248/112733598-ec32d300-8f0e-11eb-8220-387b77ba3db2.png)

Continuing thinking along those lines, a simpler open framework around the star like this one: 
![image](https://user-images.githubusercontent.com/20006248/112733738-be01c300-8f0f-11eb-8393-ad7420fd87b0.png)

with the diameter of the framework 3 or 4x the diameter of the star its enclosing...

**Comment by ljramones** [comment]
Sure I can try those and see how it works.

I can have it play as an animation where the object blinks or increases/decreases in size

**Comment by BoatrightTBC** [comment]
ok, I'll grab the mesh and send it to you for a couple.  

I kinda like this one: 

![image](https://user-images.githubusercontent.com/20006248/112734669-37e87b00-8f15-11eb-8c90-6a948b8975db.png)

**Comment by BoatrightTBC** [comment]
or, there's really really simple (This is a 3d model.)  
![image](https://user-images.githubusercontent.com/20006248/112734860-500cca00-8f16-11eb-80c9-d1f6f0c26c88.png)

**Comment by cegannon1** [comment]
And again I am lost.  I believe I wrote somewhere, recently come and at considerable length, that flashing  Labels is definitely not the way I want to go. And that reasoning is directly connected to decades of audio visual assessment in film television advertising. I have seen the same protocols and trends in computer visual design.

I am also puzzled why we are talking about theseGrid works spheres and geometric solids since I thought we had settled on a star?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cegannon1** [comment]
okay, what is this being envisioned for?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cegannon1** [comment]
If you are thinking about these eze the shape for the selected star, what's wrong with the 4 pointers and the moravian?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
I personally don’t care what object we use.

I just need it in a specific consumable format. i.e a mesh which is a universally known format in the 3D arts community

Whatever I have, I can import and display and show in the specified conditions

**Comment by BoatrightTBC** [comment]
Larry now has the 3d OBJ models to use for this, and it should be addressed.

**Comment by ljramones** [comment]
Highlight works. Still have to get it to blink
