### ISSUE TITLE
Plot Status: changes even though the plot hasn't changed

### ISSUE THREAD

**Issue by celebrith** [ljramones/trips#280]
**Describe the bug**

Have more than one data set loaded.  Plot stars from the active data set.  Change the active data set and the Plot Status: will change to "You are looking at the stars in" the new dataset, but the visible plot is still the previous dataset.  That's confusing.  

**To Reproduce**

Steps to reproduce the behavior such as:
Plot any data set, then switch to a new active data set.  The Plot status: line changes to show the new dataset name even though the plot hasn't redrawn.

**Expected behavior vs Actual**

Would like one of two behaviors.  Not sure which would be preferably by the team:

1. The Plot Status: shouldn't change until after you re-plot the stars from the new data set
2. Changing the active data set should clear the plot

**TRIPS version** 
- [ ] 0.52 
- [ ] 0.53
- [ ] 0.54
- [ ] 0.55
- [X] 0.6.7 
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [ ] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 
- [X] macOS Big Sur

**Comment by cegannon1** [comment]
Larry, a question. What was the practical driver for having more than one dataset loaded at a time?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Scott Kuntzelman ***@***.***>
Sent: Tuesday, March 23, 2021 9:51:40 PM
To: ljramones/trips ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ljramones/trips] Plot Status: changes even though the plot hasn't changed (#280)


Describe the bug

Have more than one data set loaded. Plot stars from the active data set. Change the active data set and the Plot Status: will change to "You are looking at the stars in" the new dataset, but the visible plot is still the previous dataset. That's confusing.

To Reproduce

Steps to reproduce the behavior such as:
Plot any data set, then switch to a new active data set. The Plot status: line changes to show the new dataset name even though the plot hasn't redrawn.

Expected behavior vs Actual

Would like one of two behaviors. Not sure which would be preferably by the team:

  1.  The Plot Status: shouldn't change until after you re-plot the stars from the new data set
  2.  Changing the active data set should clear the plot

TRIPS version

  *    0.52
  *    0.53
  *    0.54
  *    0.55
  *    0.6.7

Desktop (please complete the following information):

  *    IOS
  *    Windows 10
  *    Windows Vista, 7 or 8
  *    Windows XP
  *    Linux (add distribution and version to this line)
  *    macOS Big Sur

**Comment by ljramones** [comment]
@cegannon1  you can only have one dataset loaded at a time.
You can have millions or billions in the database.

What active dataset means is that if you say plot or query or search it uses the names dataset as the context for your operation.

so plot stars is a plot on the active dataset.

Selecting an active dataset only records the name of the dataset that you want to be the focus of any subsequent operation, nothing more.

**Comment by ljramones** [comment]
@celebrith I'll clear the plot and reset any side panel data for this

**Comment by ljramones** [comment]
done
