### ISSUE TITLE
Comparative length delimited pathways on the same screen

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#293]
Not a problem, but the capability is needed and I am unsure if it is present.

**Describe the solution you'd like**
Precisely what is shown in the attached video(s)

**Describe alternatives you've considered**
None. There really is no other way to show this at a single glance.

**Additional context**

**Comment by cegannon1** [comment]
Well, I can't attach a file larger than 10 mb. I'll see if I can save in a smaller format. 

Faster answer: am sending these two files to Slack, MVP thread. Between the two, you'll get a visual display of a) what I'm looking for   and    b) how it was called and accomplished by CHV    in about 3 minutes. Maybe 2.

**Comment by BoatrightTBC** [comment]
## Turning this into a spec for a requested change: 

- Rename "Transits" to "Links" 
- replace the dialog for "Find Transits between stars" with the following "Display Links" dialog which has lots more things, which I'll explain below: 
![image](https://user-images.githubusercontent.com/20006248/112734247-8ea08580-8f12-11eb-8959-933a3f86c5aa.png)

The process of SEARCHING for the transits / links programmatically doesn't change at all.  The top number above is exactly equivalent to the top number in the existing dialog, the bottom number is exactly equivalent to the lower limit in the existing dialog.  

All the rest of the stuff has to do with displaying them.  Specifically, links with lengths between two given numbers will be colored according to the color shown in the dialog. 

ChView had a mechanism for displaying the link-lines as solid, or dotted, or dot-dash lines, but Jo was just drawing 2d lines on the screen after he had positioned the stars. We should drop that. 

If the checkboxes indicating to Display or Don't display a given band are too hard to do in your model, just drop that. 

The menu choices to toggle links and link lengths on and off and the toggle links (transits) button remain the same except for the name change. 

If two bands have the same number...  if the user put in 8, 6, 4, 4, 4  or  8, 6, 4, 4, 2 you could handle it in one of two ways: 

- enforce values to be different in each box, and in descending order  
- during display, since the bands ONLY matter when we're coloring the links, two if the upper and lower limit for a band are the same, nothing gets colored that color...  

I prefer the second choice, and it makes more sense as the GENERATIING process for the links is exactly what you already have in transits using the upper and lower limits.  This is just about DISPLAY. 

If someone wanted only one color, they could do 8, 6, 6, 6, 6

**Comment by cegannon1** [comment]
Again, getting a little lost here.

Just bear in mind, and you already may be presuming this, but the actual lower limit of all possible values is 0. In other words the lowest category is always presumed to start at 0 and end at what is in the Box. So if you have 2 in the lowest Box that would The colour assigned to all links that are from 0 to 2 light years

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
this was fixed some time ago.
