### ISSUE TITLE
QUESTION:   Do partial routes display in 0.68? 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#296]
If only part of a route is available to be shown on screen, does it show?  If so, I will write the UI specs for interacting with it, if not, I'll delay for a future date. 

A portion of a route could be off screen due to re-centering, zooming, or filters.  

It's POSSIBLE that those are different situations, and if so, we should clarify them in our minds before messing with UI.  

Thanks.

**Comment by cegannon1** [comment]
agreed  Regarding clarifying if there are multiple events that caused partial routes to be displayed, and then delineating them to figure out if they can all be treated the same way or not. My guess is, probably not.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Rick Boatright ***@***.***>
Sent: Tuesday, March 30, 2021 11:14:23 PM
To: ljramones/trips ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ljramones/trips] QUESTION: Do partial routes display in 0.68? (#296)


If only part of a route is available to be shown on screen, does it show? If so, I will write the UI specs for interacting with it, if not, I'll delay for a future date.

A portion of a route could be off screen due to re-centering, zooming, or filters.

It's POSSIBLE that those are different situations, and if so, we should clarify them in our minds before messing with UI.

Thanks.

**Comment by ljramones** [comment]
Partial routes are not currently shown. I check the list of stars to see if they are all on screen. If not, then I don't show them.

There are three possible scenarios,
  - initial set of start aren't shown 
  - middle set of stars aren't present
  - end stars aren't present

in the first and end conditions, we could plot a limited segment.
Now if the middle section isn't present, we could them plot the separate segments but then it would look like two different routes

**Comment by BoatrightTBC** [comment]
For now, in the current version, I'm ok with partial routes not displaying.  We're futzing with enough stuff as it is.  We will re-visit this later.

**Comment by cegannon1** [comment]
Okay, but unless I misunderstand the significance, it is VERY important we come back to this. Otherwise, routes to stars that can’t be seen in the display will not show up….and long journeys require EXACTLY that feature.

If that understanding is correct, then

THIS IS A MAJOR ACTION ITEM.
