### ISSUE TITLE
Star Labels on grid...too many

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#3]
It is impossible to read the screen well if all of the stars names are propagated. There has to be a filter which is a sliding scale for what gets shown vs what does not. Also, I am not sure that the distance perspective (i.e. smaller scale of labels) really helps. While it does add an additional depth sense that is amplifies the FAUX 3-D representation, it comes at the price of clarity and readability. Very often it is not the nearby stars that you need to be able to scan for names, but the further ones.  This Distance shrinkage of the labels makes it pretty much impossible.

**Comment by EvilJinious1** [comment]
ok, the title says too many labels, but the description says they are too small to read.
So you want to reduce the number of labels shown and make sure that smaller labels are larger?

**Comment by cegannon1** [comment]
I would say yes, fewer labels, although the selection index is something that probably needs to be discussed. And I would say keeping the labels a uniform size and color.

Sent from my Verizon, Samsung Galaxy smartphone

________________________________

**Comment by EvilJinious1** [comment]
I'll have to think of a way to filter this. It's not straight forward

**Comment by cegannon1** [comment]
A couple of food for thought items That can be used to prioritize.
 Anything that has a formal constellation name means it's a bright enough star object  Either due to proximity, size , or both. That will make it familiar to an awful lot of people who will have stared at sky charts and have a basic familiarity with standard planet based astronomy. That's a useful piece of orientation

**Comment by EvilJinious1** [comment]
ok, that is a decision tree and and we would have to populate it. Not hard but that is the way we could solve it.

**Comment by cegannon1** [comment]
The next thing you want to consider is size. 12 and 3 are large enough to warrant consideration.

The next factor would be the stellar classes that are most likely to produce shirt sleeve planets. That would be FG and K,Magnitude V or IV

 Assuming that these  Variables generate  An aggregate number indicating whether they make a name display threshold or not, distance should be a sliding scale. In other words, we may want to think in terms of range from the observer's viewpoint in the program.

So for instance, everything inside of 10 light years automatically has its name displayed. That may not work out particularly in certain regions, but this is the basic idea. And then in bands going outward perhaps by 10 light your increments,  There is a multiplier effect.

In that way, very high valued stars such as a class 1 or 2 super giant will almost always display with in 50 to a 100 lLight years.A red Dwarf almost never would unless it's within 10 light years.The different bands would have higher multiplier valuesThe more proximal they are to the observer.

**Comment by cegannon1** [comment]
I don't know if this is possible, but I would leave  Some Room in...whatever algorithm is used. There could be other variables that will turn out to be desirable later on, such as any world that is populated, any world that is populated at a certain level, Or maybe any world that is the capital of an  Interstellar polity

**Comment by EvilJinious1** [comment]
That will probably require another dialog. 
It would filter returned data from a query and provide a transform on how its displayed according to the rules you have checked off.

**Comment by cegannon1** [comment]
Well, that would be if you are  Looking at the results of a query. But what if you're just looking at the Starfield because you center on system XYZ. How does it then choose what names. What I'm suggesting is a Mechanism whereby the moment you choose XYZ coordinates as a point of view,  It looks at all of the stars which are in the radius of  View, and generates an aggregate value. And it displays those stars with a high enough aggregate value.

**Comment by cegannon1** [comment]
For Any given location, and any given view range, there's a maximum practical number of labels that should be generated.By practical, I mean aNumber that is visually useful rather than an impairment. What that number is is something we can bat around.

**Comment by BoatrightTBC** [comment]
If we start with the idea that the current font is very small and we would like to increase it to about 1.5 times whatever it is now, then you can determine how many stars to allow to be labeled by taking a SOL centered view and reducing the radius until the overlapping or lack thereof "looks right." 

When I do that, I get the impression that between 80 and 90 labels is the extreme upper limit for my eyes. Let us pretetnd that 90 is the number... although that doesn't really matterr.  Now, how to decide which stars to label? 

Whatever we decide on, we should add "Toggle Star Name" to the popup menu that comes up when you click on a star.  

I agree that a "radius band" approach provides a reasonable way to decide on one element of the stars to display. The displayed plot has some total radius. If we divide the display radius into five shells and then allocate the number of named stars based on the shell stars are in then you get something like the following allocation: 
-  Shell ....   Allocation ....   Number if 90 total 
-    1 ....        5%  ....         4
-    2 ....        9%  ....         8
-    3 ....       18%  ....        16
-    4 ....       27%  ....        25
-    5 ....       41%  ....        37

I think we use a scoring system similar to what I've described below.  The scoring system has to be dynamic because the plot might be centered on some star 100 LY from Sol. So, once you have the stars to plot, you score each star, decide what band it's in (distance from center based), sort the scores in descending order, and put labels on the top scoring X stars in each band. 

Note that this scoring system depends VERY HIGHLY on when Larry gets the "Default additional Properties for Stars" that the search dialog displays which none of the current data does. Also, obviously we may need to play with the actual scoring numbers, tho I've been playing in the gaia data, and this seems to make sense. 

Scoring System:

- Does the star have a polity assigned to it? 20 points 
- Does the system have a world which has a population > 0? 10 points
- Does the star system have any of the other special catagories?  Fuel, military, port, etc? 10 points  for any not for each...  
- Spectral Class:   G, 5 points   F or K 4 points, A or B 3 points O or M 1 point 
- Does the star have a common name?  2 points (Does the star name not start with one of the common catalog abbreviations?  Hip, BD, G, CD, LHS, LTT) 
- Does the star have a planetary system defined in the program for it? 3 points? 

and so on.  We'll probably mess with the scoring system, but that accomplishes the goal of not overpopulating the screen.  Otherwise, if you do a hundred light years of stars, you can't read ANYTHING.  Which is why the ability to toggle the labels on and off upon selecting an individual star matters.  


Also, it occurs to me that if we're doing this, when you click on a star and get the popup menu, the stars name should be displayed there in the popup. 

Wow this  is a long comment.

**Comment by EvilJinious1** [comment]
ok, once I am through with displaying your large file, I'll think about this

**Comment by cegannon1** [comment]
I'm gonna suggest max of 60.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BoatrightTBC** [comment]
The nice thing about the approach I suggested is that, that number goes in one place and the algorythm adapts to it.  It could even be a parameter.  But yeah, it's gonna have to happen eventually.

**Comment by ljramones** [comment]
now that I have the labels behaving as requested, I will do this in 0.5.8

**Comment by ljramones** [comment]
implemented Rick's algorithm.
static label scores are calculated via the defined ruleset in Rick's spreadsheet
there is a number of visible labels in the star display preferences dialog 
the current value is calculated per plot based on distance radius.

Tested as much as I can

done
