### ISSUE TITLE
Problem with rotation in 0.6.8 preview

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#313]
Moving the mouse side to side rotates the front of the display up and down. 

Moving the mouse up and down rotates the display clockwise and counter clockwise from above. 

Does this have to do with changing the XYZ axis for display, but missing doing so for rotation?

**Comment by cegannon1** [comment]
Guys could you please send me links to libraries of 3-D frame graphics  that we could use for a second polity indicator?  I've got to find one that is based on curves rather than lines.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Rick Boatright ***@***.***>
Sent: Sunday, April 4, 2021 12:35:47 AM
To: ljramones/trips ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ljramones/trips] Problem with rotation in 0.6.8 preview (#313)


Moving the mouse side to side rotates the front of the display up and down.

Moving the mouse up and down rotates the display clockwise and counter clockwise from above.

Does this have to do with changing the XYZ axis for display, but missing doing so for rotation?

**Comment by ljramones** [comment]
yes, I assume so. I'll figure out some transform

**Comment by ljramones** [comment]
I played around with tons of rotational axis and delta values and I think I conquered this.
