### ISSUE TITLE
Change Menu to desired look

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#317]
as Rick's spreadsheet dictates

**Comment by cegannon1** [comment]
Larry, for whom was this intended?

From: LJ Ramones ***@***.***
Sent: Tuesday, April 13, 2021 9:32 AM
To: ljramones/trips
Cc: Subscribed
Subject: [ljramones/trips] Change Menu to desired look (#317)


Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Describe the solution you'd like
A clear and concise description of what you want to happen.

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

Additional context
Add any other context or screenshots about the feature request here.

**Comment by ljramones** [comment]
I didn’t finish the description

Just updated

**Comment by cegannon1** [comment]
Okay. I only see these as fast-action emails, so have no sense of the ongoing process on GitHub. Except when you refer to a graphic or other item to inspect, as you did re: the route distance colors.  ;)

**Comment by ljramones** [comment]
There is usually a link below where you can see the whole thread

**Comment by cegannon1** [comment]
Yes, I know. But when I am on my cell, it doesn’t read correctly. So I don’t get to it until later (sometimes, much later).

**Comment by ljramones** [comment]
worked through File, Edit and View. 
There are some open questions on these but I will continue ahead with the rest and circle back ala Jen Psaki to get answers

**Comment by ljramones** [comment]
I've made the changes but I need to finish the functions
