### ISSUE TITLE
Creating a long route

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#332]
If you download the trips-normal-names-270.xlsx dataset from https://tbcsoftware.com/trips/Datasets and display stars out to 140 LY, you should be able to find two stars, G 250-29   and 55 Tauri 

These are a little over 100 ly apart.  

Any effort to make a route between them gets "Too many stars."  

How can we segment so that we can get a route?  This is the route that started the entire project of TRIPS.

**Comment by cegannon1** [comment]
If Rick is talking about 140 LY from Sol, I think you're going to need to expand to about 155 LY range. 55 Tauri is I think​ at ~ 152 LY.

Thanks!
________________________________
From: Rick Boatright ***@***.***>
Sent: Tuesday, May 4, 2021 4:09 PM
To: ljramones/trips ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ljramones/trips] Creating a long route (#332)


If you download the trips-normal-names-270.xlsx dataset from https://tbcsoftware.com/trips/Datasets and display stars out to 140 LY, you should be able to find two stars, G 250-29 and 55 Tauri

These are a little over 100 ly apart.

Any effort to make a route between them gets "Too many stars."

How can we segment so that we can get a route? This is the route that started the entire project of TRIPS.

**Comment by BoatrightTBC** [comment]
My thoughts on long routes:


So, assuming there are WAY too many stars on the screen to use the usual methods of finding a route, there are some optimizations we can do to cut down the number of stars to search through.


I would want to pop up a message like: “Wow, lots of stars to consider, this will take a while, continue?”


Given two stars at x,y,z and x1, y1, z1 those two points define a line in 3 space that can be considered as the diagonal of a cube.


[data:]


As a first cut, we can consider for routes only those stars inside the cube. While it’s certainly possible that the only route wraps outside the cube, there’s no reason to assume that and this greatly reduces the number of stars considered unless the two stars are on opposite sides of the dataset.


The stars to be considered will need to be constrained so that the considered stars X2 is > X and less than x1. And similarly for y and z.


If that still leaves too many stars to run the route finding against, we can further constrain the stars by considering the line defined by the two points, and a cylindar of some radius around that line.


[cid:14f97dea-97d8-430b-8b58-b9f49dfc3b7c]














A point is on the line if

[cid:a880b479-dad0-455c-b6a8-170f53aff3f0]




and that point is in the cylinder if the Xnew considered is between x + r and x – r and similarly for y and z.


This allows us to quickly eliminate stars outside the cylinder, and as we decrease R we can eventually reach a number of stars we can run the route finding against.


What if, at that point, the route finder fails?


Ida know. The problem is that with hundreds of thousands of stars, there with a jump length of 0 to 8, there are an average of four potential links for each star. Starting from star 1, searching through all the links to build a tree that eventually reaches star 2, the tree becomes vast quickly.


In the case of a 100 light year route search, the second possibility is to find an essentially random star about 1/5 the way from A to B, cut the star set down to that radius, and find a route from A to intermediate 1, then, pick a random star 2/5 of the way from A to B and cut down and find a route from intermediate 1 to intermediate 2, lather rinse repeat.


If at some point the hunt fails, go back and choose a different intermediate.


Nothing is going to be easy or fast for a route when there are a quarter of a million stars in consideration.


________________________________

**Comment by ljramones** [comment]
getting closer with this.
I implemented a more optimized search that uses all the cores that are available on the computer. Also a set of smaller data structures for representation.
These are stored and displayed in the side panel for routing.
working on determining and displaying a partial route. A partial is one where only some of the stars are visible. 
There are several cases for this. 
- the first sequence of n (out of m total route stars) are visible
- the last sequence of n (out of m total route stars) are visible (first of m-n are off-screen)
- there are multiple independent sequences of stars visible but they are disjoint due to the middle sequences being off-screen.

In the last case (multiple disjoint sequences), we need to drow separate routes for these.
I am finishing up the partial route code and next will be the drawing portion.
I am put the special end points into the next release

**Comment by cegannon1** [comment]
Great.

a However, bear on mind some very old computer s will be USING TRIPS.

We need to have a way of telling /advising folks in program that their hardware is too slow or just unable to run certain auto-routing processes. Can the program survey the on board resources to effect that?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ljramones** [comment]
I added a progress bar with a visual guide to how far along it is moving. I tried it out with my laptop
if someone wants to bail, then they can cancel without penalty.

**Comment by ljramones** [comment]
finally done
