### ISSUE TITLE
Data missing after CHV import

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#79]
**Describe the bug**

After importing a CHV file, there are data fields which were in the CHV data that are not being imported.  

**To Reproduce**

* Load the TERRAGRP.chv file, which is the smallest I have. 
* Look at Sol.  In the notes you will see that it says "Initial Import" but the notes field in the CHV file says 
`9 planets,asteroids,KuiperBelt,DiaOortCloud=0.4ly;"Sun"`

**Expected behavior vs Actual**

All the important fields in the CHV file should be mapped onto TRIPS fields. It is particularly troubling to not import the notes. 

Let's consider Sol and Proxima Centauri as examples. From the CHV Documentation at http://members.nova.org/~sol/chview/chvb.htm we're told that the following fields exist for each object: 

| CHV definition                          | Sol Value | Proxima Centauri | Import result | 
| --------------------------------------- | --------- | ---------------- | ------------- |
| cjcName - string -Proper Name of Place  | Earth-Sol |  null            | Ignored       |
| starName -string -Official name of star | Sol       | Proxima Centauri | OK            |
| dToEarth -double -Distance to earth     | 0         | 4.22             | OK            |
| Spectra -string -Spectra                | G2V       | M5.5Ve           | OK            |
| Mass -double -Collapsed mass            | 1         | 0.111            | Ignored       |
| ActualMass -double -Uncollapsed mass    | 1         | 0.11             | Ignored       |
| ords[0] -double -Galactic coordinates   | 0         | -1.54            | X OK          |
| ords[1] -double -                       | 0         | -1.18            | Y OK          |
| ords[2] -double -                       |           | -3.75            | Z OK          |
| Constellation -string -Constellation    | null      | Centaurus        | Ignored       |
| Comment -string -Comment                | 55 Chars  | 40  Char         | Ignored Should be notes |
| Selected -int -Selected or not          |           |                  | na |
| index -int -Index in file               |           |                  | na |
| Group -int -Group of star               |           |                  | na |
| Complex info regarding binary stars     | don't care| don't care       | na |
| Links (which we call Routes)            |           | 4 linked stars   | We'll discuss routes later |

I don't know why we don't have a constellation field, but it ought to be easy to add. Similarly, I don't know why we're dropping the mass field, but I think it would be good to add it (a single value from the "ActualMass" field unless it's empty and the Mass field isn't. 

I have no interest in storing or picking up that stars are in binary or trinary sets with their orbital radius and period, but for purposes of completeness, the CHV file has the following for Alpha Centauri A: 
`AB:a=24AU,sep=11-35AU;e=0.52;P=80yr;` 
which I presume to mean 
* This is the A star of an AB pair. 
* Average seperation is 24 AU
* Seperation between the stars varies from 11 to 35 AU which can be equated to the major a lund minor axis of the orbit. 
* the Eccentricity of the Orbit is 0.52
* the Period of the orbit is 80 years. 

Similarly, the info for Ursa Major -- which is a double star identified by spectral lines --  says: 
`Var,spec.dou.:a=7.62",20.1AU;P=50.090yr;e=0.58`

Here the coding "a=7.62" is very odd if the other star's a value was in AU and this in arc-seconds. But then we get the reasonable 20.1 AU... perhaps we're to be psychic?  Then, a period of 50.090 years and an excentricity of 0.58.  Looking at the chv data file, the coding for binaries is SO inconsistant that I think we gave up the last time we looked into this. 

In any event **I do NOT propose we try to import subsidiary data like planets from CHV files.** 

I note once again that the file format page at http://members.nova.org/~sol/chview/chvb.htm lies about everything after comment... it claims that the entire data entry for the object is recursively entered for subsidiary objects This would mean that a star system with five known planets would have five subsidiary records many of which (spectral class for example) are pointless for a planet.  When we get around to storing information about the elements of a solar system, those will doubtless be in another table related to the star table by some unique key. We do have a choice on the context menu that pops up when you click on a star "Enter System" which is doubtless where planet and other such data would be stored, but we've never discussed that data structure or editing/viewing it.  That's for a later time.
`
Note that the CHV data had routes embedded in it.  We have not (publicly) discussed how routes will be stored in TRIPS, nor how or if we will import them from CHV files.  That's an open issue for discussion, not a current bug or enhancement. Doubtless Route information is going to be stored in another table. We've never discussed what data-structure to use, but this isn't the place. 

**TRIPS version** 
- [ ] 0.52 
- [X] 0.53
- [ ] 0.54
- [ ] 0.55
 
**Desktop (please complete the following information):** 
<!-- Move the X to the right line =-> 
- [ ] IOS 
- [X] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line)

**Comment by cegannon1** [comment]
While I understand where they come from, a lot ofthese assertions and conclusions Are taking us  Way off course from our actual objective.

We need fewer not less or data points. At least for the data sets that will be used to drive the program, which is predominantly going to be used by authors and gamers. Much of the data that you are interested in curated will be of intense interest to astronomers but no one else. And right now, there is little chance that this product would be used by a great number of them. At any rate. That is not the Reason why it is being created.

I remain very mindful of the fact that I desperately need this program to function in time for me to use it as A very ascensional narrative tool for the next set of Cain books.When we run into moments like this, the answer is to simplify, not complicate.

Lastly, while I don't have time to do it now, it is imperative that there is a clear understanding of what is crucial data and what is not. For instance, For anybody who is trying to work as  An author or a referee, the various astrophysical measures of a multiple star system are incredibly important to retain. So things such as aphelion and perihelion, period, and eccentricity Are absolutely crucial.

 That does not mean that they will all be available now, and God knows, that Jo  Was extremely inconsistent in his notes and data recording. So the trick here is to make sure that we have the placeholders to fill them in later, even if is not clear what they are right now.

 Another reason this is important is exoplanets. Be tween re discovery and recalculations, all we can do is leave a dataslot and room for notes.  Example. Right now, there are so many systems which are going through revision regarding what various astronomers believe the data indicates regarding how many EXO planets are there and in what relationship to each other. That is going to continue. That is  Data of extreme interest to any author and any gamer that is trying to stay close to observed actual properties in the universe. However, there is absolutely no way we can task this program to even offer a consistent way for recording all this data.you can maybe create boxes to fill in to keep track of how many planets are thought to exist,  And it would be good to leave a space for general notes. However,  Not even the astronomical community has arrived at a single universal format about how best to describe and define the current models, and their respective  Theoretical provenances, Especially since each one tends to evolve over the course of time.

And  At the same time,  The program will be least daunting for people considering editing the data if the string is shorter and more manageable.



At some point, there was a list of crucial stellar data characteristics that were needed. I do not have the time to try to locate that. I will try to address that soon.

 But the rule of thumb is going to be this. if a piece of data is  He central or highly useful for generating planets or conditions in the system, it's probably going to be retained. If it is of astronomical  Interests that does not impact such considerations, it's probably best reserved for the dull database, but not the datasets driving the program.



________________________________

**Comment by cegannon1** [comment]
Had to  Respond tothis at 1:00 a.m. in the morning and was using Voice to text. Please try to bear with me. But I did not want this running away.

I'm going to be transparent and say that right now, I am having a great deal of reservations about how a lot of things being identified as bugs or problems are then also turning into decision pathways about what the program is going to do or not. We need to disambiguate  Issues that are about functionality and operation, and those which bleed over into what the program is actually going to do and deliver.

When it comes to the latter,That needs to go through me before it becomes a new set of imperatives that Larry has to worry about.So we'd probably need to handle some of these issues a little differently, and they probably need to be on the private channel.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cegannon1** [comment]
We have all that. And, with 0.53 you now have your required stuff for your
fiction work, and the ability to edit that data and query it. (Or at least
almost)

The system is saving routes,  etc. The issue is, in importing your old chv
files, we're nitot yet getting the routes from it, nor are we getting the
fields you used for polity etc.

The astrographic stuff is done. Its notes and those fields you need so much
that we're focusing on.  Any mention of the astrographic stuff is way down
the important list.

Im looking at some of your old chv files in chv in an xp virtual to try to
figure out how they were stored.

Its VERY close to what you need. You should be able to actually start USING
it with te 054 version.

We havent lost the vision, its just we HAVE to figure out the chv files, or
you get to reenter all your fiction data from scratch.

**Comment by cegannon1** [comment]
Its the NOTES field i was particularly wanting, which serms important.

**Comment by ljramones** [comment]
all missing fields  added
